/*
 * Summary: error handling
 * Description: the API used to report errors
 *
 * Copy: See Copyright for the status of this software.
 *
 * Author: Daniel Veillard
 */

#include <libxml/parser.h>

#ifndef __XML_ERROR_H__
#define __XML_ERROR_H__

#ifdef __cplusplus
extern "C" {
#endif

/**
 * xmlErrorLevel:
 *
 * Indicates the level of an error
 */
typedef enum {
    XML_ERR_NONE = 0,
    XML_ERR_WARNING = 1,	/* A simple warning */
    XML_ERR_ERROR = 2,		/* A recoverable error */
    XML_ERR_FATAL = 3		/* A fatal error */
} xmlErrorLevel;

/**
 * xmlErrorDomain:
 *
 * Indicates where an error may have come from
 */
typedef enum {
    XML_FROM_NONE = 0,
    XML_FROM_PARSER,	/* The XML parser */
    XML_FROM_TREE,	/* The tree module */
    XML_FROM_NAMESPACE,	/* The XML Namespace module */
    XML_FROM_DTD,	/* The XML DTD validation with parser context*/
    XML_FROM_HTML,	/* The HTML parser */
    XML_FROM_MEMORY,	/* The memory allocator */
    XML_FROM_OUTPUT,	/* The serialization code */
    XML_FROM_IO,	/* The Input/Output stack */
    XML_FROM_FTP,	/* The FTP module */
    XML_FROM_HTTP,	/* The HTTP module */
    XML_FROM_XINCLUDE,	/* The XInclude processing */
    XML_FROM_XPATH,	/* The XPath module */
    XML_FROM_XPOINTER,	/* The XPointer module */
    XML_FROM_REGEXP,	/* The regular expressions module */
    XML_FROM_DATATYPE,	/* The W3C XML Schemas Datatype module */
    XML_FROM_SCHEMASP,	/* The W3C XML Schemas parser module */
    XML_FROM_SCHEMASV,	/* The W3C XML Schemas validation module */
    XML_FROM_RELAXNGP,	/* The Relax-NG parser module */
    XML_FROM_RELAXNGV,	/* The Relax-NG validator module */
    XML_FROM_CATALOG,	/* The Catalog module */
    XML_FROM_C14N,	/* The Canonicalization module */
    XML_FROM_XSLT,	/* The XSLT engine from libxslt */
    XML_FROM_VALID,	/* The XML DTD validation with valid context */
    XML_FROM_CHECK,	/* The error checking module */
    XML_FROM_WRITER,	/* The xmlwriter module */
    XML_FROM_MODULE,	/* The dynamically loaded module module*/
    XML_FROM_I18N,	/* The module handling character conversion */
    XML_FROM_SCHEMATRONV,/* The Schematron validator module */
    XML_FROM_BUFFER,    /* The buffers module */
    XML_FROM_URI        /* The URI module */
} xmlErrorDomain;

/**
 * xmlError:
 *
 * An XML Error instance.
 */

typedef struct _xmlError xmlError;
typedef xmlError *xmlErrorPtr;
struct _xmlError {
    int		domain;	/* What part of the library raised this error */
    int		code;	/* The error code, e.g. an xmlParserError */
    char       *message;/* human-readable informative error message */
    xmlErrorLevel level;/* how consequent is the error */
    char       *file;	/* the filename */
    int		line;	/* the line number if available */
    char       *str1;	/* extra string information */
    char       *str2;	/* extra string information */
    char       *str3;	/* extra string information */
    int		int1;	/* extra number information */
    int		int2;	/* error column # or 0 if N/A (todo: rename field when we would brk ABI) */
    void       *ctxt;   /* the parser context if available */
    void       *node;   /* the node in the tree */
};

/**
 * xmlParserError:
 *
 * This is an error that the XML (or HTML) parser can generate
 */
typedef enum {
    XML_ERR_OK = 0,
    XML_ERR_INTERNAL_ERROR, /* 1 */
    XML_ERR_NO_MEMORY, /* 2 */
    XML_ERR_DOCUMENT_START, /* 3 */
    XML_ERR_DOCUMENT_EMPTY, /* 4 */
    XML_ERR_DOCUMENT_END, /* 5 */
    XML_ERR_INVALID_HEX_CHARREF, /* 6 */
    XML_ERR_INVALID_DEC_CHARREF, /* 7 */
    XML_ERR_INVALID_CHARREF, /* 8 */
    XML_ERR_INVALID_CHAR, /* 9 */
    XML_ERR_CHARREF_AT_EOF, /* 10 */
    XML_ERR_CHARREF_IN_PROLOG, /* 11 */
    XML_ERR_CHARREF_IN_EPILOG, /* 12 */
    XML_ERR_CHARREF_IN_DTD, /* 13 */
    XML_ERR_ENTITYREF_AT_EOF, /* 14 */
    XML_ERR_ENTITYREF_IN_PROLOG, /* 15 */
    XML_ERR_ENTITYREF_IN_EPILOG, /* 16 */
    XML_ERR_ENTITYREF_IN_DTD, /* 17 */
    XML_ERR_PEREF_AT_EOF, /* 18 */
    XML_ERR_PEREF_IN_PROLOG, /* 19 */
    XML_ERR_PEREF_IN_EPILOG, /* 20 */
    XML_ERR_PEREF_IN_INT_SUBSET, /* 21 */
    XML_ERR_ENTITYREF_NO_NAME, /* 22 */
    XML_ERR_ENTITYREF_SEMICOL_MISSING, /* 23 */
    XML_ERR_PEREF_NO_NAME, /* 24 */
    XML_ERR_PEREF_SEMICOL_MISSING, /* 25 */
    XML_ERR_UNDECLARED_ENTITY, /* 26 */
    XML_WAR_UNDECLARED_ENTITY, /* 27 */
    XML_ERR_UNPARSED_ENTITY, /* 28 */
    XML_ERR_ENTITY_IS_EXTERNAL, /* 29 */
    XML_ERR_ENTITY_IS_PARAMETER, /* 30 */
    XML_ERR_UNKNOWN_ENCODING, /* 31 */
    XML_ERR_UNSUPPORTED_ENCODING, /* 32 */
    XML_ERR_STRING_NOT_STARTED, /* 33 */
    XML_ERR_STRING_NOT_CLOSED, /* 34 */
    XML_ERR_NS_DECL_ERROR, /* 35 */
    XML_ERR_ENTITY_NOT_STARTED, /* 36 */
    XML_ERR_ENTITY_NOT_FINISHED, /* 37 */
    XML_ERR_LT_IN_ATTRIBUTE, /* 38 */
    XML_ERR_ATTRIBUTE_NOT_STARTED, /* 39 */
    XML_ERR_ATTRIBUTE_NOT_FINISHED, /* 40 */
    XML_ERR_ATTRIBUTE_WITHOUT_VALUE, /* 41 */
    XML_ERR_ATTRIBUTE_REDEFINED, /* 42 */
    XML_ERR_LITERAL_NOT_STARTED, /* 43 */
    XML_ERR_LITERAL_NOT_FINISHED, /* 44 */
    XML_ERR_COMMENT_NOT_FINISHED, /* 45 */
    XML_ERR_PI_NOT_STARTED, /* 46 */
    XML_ERR_PI_NOT_FINISHED, /* 47 */
    XML_ERR_NOTATION_NOT_STARTED, /* 48 */
    XML_ERR_NOTATION_NOT_FINISHED, /* 49 */
    XML_ERR_ATTLIST_NOT_STARTED, /* 50 */
    XML_ERR_ATTLIST_NOT_FINISHED, /* 51 */
    XML_ERR_MIXED_NOT_STARTED, /* 52 */
    XML_ERR_MIXED_NOT_FINISHED, /* 53 */
    XML_ERR_ELEMCONTENT_NOT_STARTED, /* 54 */
    XML_ERR_ELEMCONTENT_NOT_FINISHED, /* 55 */
    XML_ERR_XMLDECL_NOT_STARTED, /* 56 */
    XML_ERR_XMLDECL_NOT_FINISHED, /* 57 */
    XML_ERR_CONDSEC_NOT_STARTED, /* 58 */
    XML_ERR_CONDSEC_NOT_FINISHED, /* 59 */
    XML_ERR_EXT_SUBSET_NOT_FINISHED, /* 60 */
    XML_ERR_DOCTYPE_NOT_FINISHED, /* 61 */
    XML_ERR_MISPLACED_CDATA_END, /* 62 */
    XML_ERR_CDATA_NOT_FINISHED, /* 63 */
    XML_ERR_RESERVED_XML_NAME, /* 64 */
    XML_ERR_SPACE_REQUIRED, /* 65 */
    XML_ERR_SEPARATOR_REQUIRED, /* 66 */
    XML_ERR_NMTOKEN_REQUIRED, /* 67 */
    XML_ERR_NAME_REQUIRED, /* 68 */
    XML_ERR_PCDATA_REQUIRED, /* 69 */
    XML_ERR_URI_REQUIRED, /* 70 */
    XML_ERR_PUBID_REQUIRED, /* 71 */
    XML_ERR_LT_REQUIRED, /* 72 */
    XML_ERR_GT_REQUIRED, /* 73 */
    XML_ERR_LTSLASH_REQUIRED, /* 74 */
    XML_ERR_EQUAL_REQUIRED, /* 75 */
    XML_ERR_TAG_NAME_MISMATCH, /* 76 */
    XML_ERR_TAG_NOT_FINISHED, /* 77 */
    XML_ERR_STANDALONE_VALUE, /* 78 */
    XML_ERR_ENCODING_NAME, /* 79 */
    XML_ERR_HYPHEN_IN_COMMENT, /* 80 */
    XML_ERR_INVALID_ENCODING, /* 81 */
    XML_ERR_EXT_ENTITY_STANDALONE, /* 82 */
    XML_ERR_CONDSEC_INVALID, /* 83 */
    XML_ERR_VALUE_REQUIRED, /* 84 */
    XML_ERR_NOT_WELL_BALANCED, /* 85 */
    XML_ERR_EXTRA_CONTENT, /* 86 */
    XML_ERR_ENTITY_CHAR_ERROR, /* 87 */
    XML_ERR_ENTITY_PE_INTERNAL, /* 88 */
    XML_ERR_ENTITY_LOOP, /* 89 */
    XML_ERR_ENTITY_BOUNDARY, /* 90 */
    XML_ERR_INVALID_URI, /* 91 */
    XML_ERR_URI_FRAGMENT, /* 92 */
    XML_WAR_CATALOG_PI, /* 93 */
    XML_ERR_NO_DTD, /* 94 */
    XML_ERR_CONDSEC_INVALID_KEYWORD, /* 95 */
    XML_ERR_VERSION_MISSING, /* 96 */
    XML_WAR_UNKNOWN_VERSION, /* 97 */
    XML_WAR_LANG_VALUE, /* 98 */
    XML_WAR_NS_URI, /* 99 */
    XML_WAR_NS_URI_RELATIVE, /* 100 */
    XML_ERR_MISSING_ENCODING, /* 101 */
    XML_WAR_SPACE_VALUE, /* 102 */
    XML_ERR_NOT_STANDALONE, /* 103 */
    XML_ERR_ENTITY_PROCESSING, /* 104 */
    XML_ERR_NOTATION_PROCESSING, /* 105 */
    XML_WAR_NS_COLUMN, /* 106 */
    XML_WAR_ENTITY_REDEFINED, /* 107 */
    XML_ERR_UNKNOWN_VERSION, /* 108 */
    XML_ERR_VERSION_MISMATCH, /* 109 */
    XML_ERR_NAME_TOO_LONG, /* 110 */
    XML_ERR_USER_STOP, /* 111 */
    XML_NS_ERR_XML_NAMESPACE = 200,
    XML_NS_ERR_UNDEFINED_NAMESPACE, /* 201 */
    XML_NS_ERR_QNAME, /* 202 */
    XML_NS_ERR_ATTRIBUTE_REDEFINED, /* 203 */
    XML_NS_ERR_EMPTY, /* 204 */
    XML_NS_ERR_COLON, /* 205 */
    XML_DTD_ATTRIBUTE_DEFAULT = 500,
    XML_DTD_ATTRIBUTE_REDEFINED, /* 501 */
    XML_DTD_ATTRIBUTE_VALUE, /* 502 */
    XML_DTD_CONTENT_ERROR, /* 503 */
    XML_DTD_CONTENT_MODEL, /* 504 */
    XML_DTD_CONTENT_NOT_DETERMINIST, /* 505 */
    XML_DTD_DIFFERENT_PREFIX, /* 506 */
    XML_DTD_ELEM_DEFAULT_NAMESPACE, /* 507 */
    XML_DTD_ELEM_NAMESPACE, /* 508 */
    XML_DTD_ELEM_REDEFINED, /* 509 */
    XML_DTD_EMPTY_NOTATION, /* 510 */
    XML_DTD_ENTITY_TYPE, /* 511 */
    XML_DTD_ID_FIXED, /* 512 */
    XML_DTD_ID_REDEFINED, /* 513 */
    XML_DTD_ID_SUBSET, /* 514 */
    XML_DTD_INVALID_CHILD, /* 515 */
    XML_DTD_INVALID_DEFAULT, /* 516 */
    XML_DTD_LOAD_ERROR, /* 517 */
    XML_DTD_MISSING_ATTRIBUTE, /* 518 */
    XML_DTD_MIXED_CORRUPT, /* 519 */
    XML_DTD_MULTIPLE_ID, /* 520 */
    XML_DTD_NO_DOC, /* 521 */
    XML_DTD_NO_DTD, /* 522 */
    XML_DTD_NO_ELEM_NAME, /* 523 */
    XML_DTD_NO_PREFIX, /* 524 */
    XML_DTD_NO_ROOT, /* 525 */
    XML_DTD_NOTATION_REDEFINED, /* 526 */
    XML_DTD_NOTATION_VALUE, /* 527 */
    XML_DTD_NOT_EMPTY, /* 528 */
    XML_DTD_NOT_PCDATA, /* 529 */
    XML_DTD_NOT_STANDALONE, /* 530 */
    XML_DTD_ROOT_NAME, /* 531 */
    XML_DTD_STANDALONE_WHITE_SPACE, /* 532 */
    XML_DTD_UNKNOWN_ATTRIBUTE, /* 533 */
    XML_DTD_UNKNOWN_ELEM, /* 534 */
    XML_DTD_UNKNOWN_ENTITY, /* 535 */
    XML_DTD_UNKNOWN_ID, /* 536 */
    XML_DTD_UNKNOWN_NOTATION, /* 537 */
    XML_DTD_STANDALONE_DEFAULTED, /* 538 */
    XML_DTD_XMLID_VALUE, /* 539 */
    XML_DTD_XMLID_TYPE, /* 540 */
    XML_DTD_DUP_TOKEN, /* 541 */
    XML_HTML_STRUCURE_ERROR = 800,
    XML_HTML_UNKNOWN_TAG, /* 801 */
    XML_RNGP_ANYNAME_ATTR_ANCESTOR = 2026,
    XML_RNGP_ATTR_CONFLICT, /* 2026 */
    XML_RNGP_ATTRIBUTE_CHILDREN, /* 2026 */
    XML_RNGP_ATTRIBUTE_CONTENT, /* 2026 */
    XML_RNGP_ATTRIBUTE_EMPTY, /* 2026 */
    XML_RNGP_ATTRIBUTE_NOOP, /* 2026 */
    XML_RNGP_CHOICE_CONTENT, /* 2026 */
    XML_RNGP_CHOICE_EMPTY, /* 2026 */
    XML_RNGP_CREATE_FAILURE, /* 2026 */
    XML_RNGP_DATA_CONTENT, /* 2026 */
    XML_RNGP_DEF_CHOICE_AND_INTERLEAVE, /* 2026 */
    XML_RNGP_DEFINE_CREATE_FAILED, /* 2026 */
    XML_RNGP_DEFINE_EMPTY, /* 2026 */
    XML_RNGP_DEFINE_MISSING, /* 2026 */
    XML_RNGP_DEFINE_NAME_MISSING, /* 2026 */
    XML_RNGP_ELEM_CONTENT_EMPTY, /* 2026 */
    XML_RNGP_ELEM_CONTENT_ERROR, /* 2026 */
    XML_RNGP_ELEMENT_EMPTY, /* 2026 */
    XML_RNGP_ELEMENT_CONTENT, /* 2026 */
    XML_RNGP_ELEMENT_NAME, /* 2026 */
    XML_RNGP_ELEMENT_NO_CONTENT, /* 2026 */
    XML_RNGP_ELEM_TEXT_CONFLICT, /* 2026 */
    XML_RNGP_EMPTY, /* 2026 */
    XML_RNGP_EMPTY_CONSTRUCT, /* 2026 */
    XML_RNGP_EMPTY_CONTENT, /* 2026 */
    XML_RNGP_EMPTY_NOT_EMPTY, /* 2026 */
    XML_RNGP_ERROR_TYPE_LIB, /* 2026 */
    XML_RNGP_EXCEPT_EMPTY, /* 2026 */
    XML_RNGP_EXCEPT_MISSING, /* 2026 */
    XML_RNGP_EXCEPT_MULTIPLE, /* 2026 */
    XML_RNGP_EXCEPT_NO_CONTENT, /* 2026 */
    XML_RNGP_EXTERNALREF_EMTPY, /* 2026 */
    XML_RNGP_EXTERNAL_REF_FAILURE, /* 2026 */
    XML_RNGP_EXTERNALREF_RECURSE, /* 2026 */
    XML_RNGP_FORBIDDEN_ATTRIBUTE, /* 2026 */
    XML_RNGP_FOREIGN_ELEMENT, /* 2026 */
    XML_RNGP_GRAMMAR_CONTENT, /* 2026 */
    XML_RNGP_GRAMMAR_EMPTY, /* 2026 */
    XML_RNGP_GRAMMAR_MISSING, /* 2026 */
    XML_RNGP_GRAMMAR_NO_START, /* 2026 */
    XML_RNGP_GROUP_ATTR_CONFLICT, /* 2026 */
    XML_RNGP_HREF_ERROR, /* 2026 */
    XML_RNGP_INCLUDE_EMPTY, /* 2026 */
    XML_RNGP_INCLUDE_FAILURE, /* 2026 */
    XML_RNGP_INCLUDE_RECURSE, /* 2026 */
    XML_RNGP_INTERLEAVE_ADD, /* 2026 */
    XML_RNGP_INTERLEAVE_CREATE_FAILED, /* 2026 */
    XML_RNGP_INTERLEAVE_EMPTY, /* 2026 */
    XML_RNGP_INTERLEAVE_NO_CONTENT, /* 2026 */
    XML_RNGP_INVALID_DEFINE_NAME, /* 2026 */
    XML_RNGP_INVALID_URI, /* 2026 */
    XML_RNGP_INVALID_VALUE, /* 2026 */
    XML_RNGP_MISSING_HREF, /* 2026 */
    XML_RNGP_NAME_MISSING, /* 2026 */
    XML_RNGP_NEED_COMBINE, /* 2026 */
    XML_RNGP_NOTALLOWED_NOT_EMPTY, /* 2026 */
    XML_RNGP_NSNAME_ATTR_ANCESTOR, /* 2026 */
    XML_RNGP_NSNAME_NO_NS, /* 2026 */
    XML_RNGP_PARAM_FORBIDDEN, /* 2026 */
    XML_RNGP_PARAM_NAME_MISSING, /* 2026 */
    XML_RNGP_PARENTREF_CREATE_FAILED, /* 2026 */
    XML_RNGP_PARENTREF_NAME_INVALID, /* 2026 */
    XML_RNGP_PARENTREF_NO_NAME, /* 2026 */
    XML_RNGP_PARENTREF_NO_PARENT, /* 2026 */
    XML_RNGP_PARENTREF_NOT_EMPTY, /* 2026 */
    XML_RNGP_PARSE_ERROR, /* 2026 */
    XML_RNGP_PAT_ANYNAME_EXCEPT_ANYNAME, /* 2026 */
    XML_RNGP_PAT_ATTR_ATTR, /* 2026 */
    XML_RNGP_PAT_ATTR_ELEM, /* 2026 */
    XML_RNGP_PAT_DATA_EXCEPT_ATTR, /* 2026 */
    XML_RNGP_PAT_DATA_EXCEPT_ELEM, /* 2026 */
    XML_RNGP_PAT_DATA_EXCEPT_EMPTY, /* 2026 */
    XML_RNGP_PAT_DATA_EXCEPT_GROUP, /* 2026 */
    XML_RNGP_PAT_DATA_EXCEPT_INTERLEAVE, /* 2026 */
    XML_RNGP_PAT_DATA_EXCEPT_LIST, /* 2026 */
    XML_RNGP_PAT_DATA_EXCEPT_ONEMORE, /* 2026 */
    XML_RNGP_PAT_DATA_EXCEPT_REF, /* 2026 */
    XML_RNGP_PAT_DATA_EXCEPT_TEXT, /* 2026 */
    XML_RNGP_PAT_LIST_ATTR, /* 2026 */
    XML_RNGP_PAT_LIST_ELEM, /* 2026 */
    XML_RNGP_PAT_LIST_INTERLEAVE, /* 2026 */
    XML_RNGP_PAT_LIST_LIST, /* 2026 */
    XML_RNGP_PAT_LIST_REF, /* 2026 */
    XML_RNGP_PAT_LIST_TEXT, /* 2026 */
    XML_RNGP_PAT_NSNAME_EXCEPT_ANYNAME, /* 2026 */
    XML_RNGP_PAT_NSNAME_EXCEPT_NSNAME, /* 2026 */
    XML_RNGP_PAT_ONEMORE_GROUP_ATTR, /* 2026 */
    XML_RNGP_PAT_ONEMORE_INTERLEAVE_ATTR, /* 2026 */
    XML_RNGP_PAT_START_ATTR, /* 2026 */
    XML_RNGP_PAT_START_DATA, /* 2026 */
    XML_RNGP_PAT_START_EMPTY, /* 2026 */
    XML_RNGP_PAT_START_GROUP, /* 2026 */
    XML_RNGP_PAT_START_INTERLEAVE, /* 2026 */
    XML_RNGP_PAT_START_LIST, /* 2026 */
    XML_RNGP_PAT_START_ONEMORE, /* 2026 */
    XML_RNGP_PAT_START_TEXT, /* 2026 */
    XML_RNGP_PAT_START_VALUE, /* 2026 */
    XML_RNGP_PREFIX_UNDEFINED, /* 2026 */
    XML_RNGP_REF_CREATE_FAILED, /* 2026 */
    XML_RNGP_REF_CYCLE, /* 2026 */
    XML_RNGP_REF_NAME_INVALID, /* 2026 */
    XML_RNGP_REF_NO_DEF, /* 2026 */
    XML_RNGP_REF_NO_NAME, /* 2026 */
    XML_RNGP_REF_NOT_EMPTY, /* 2026 */
    XML_RNGP_START_CHOICE_AND_INTERLEAVE, /* 2026 */
    XML_RNGP_START_CONTENT, /* 2026 */
    XML_RNGP_START_EMPTY, /* 2026 */
    XML_RNGP_START_MISSING, /* 2026 */
    XML_RNGP_TEXT_EXPECTED, /* 2026 */
    XML_RNGP_TEXT_HAS_CHILD, /* 2026 */
    XML_RNGP_TYPE_MISSING, /* 2026 */
    XML_RNGP_TYPE_NOT_FOUND, /* 2026 */
    XML_RNGP_TYPE_VALUE, /* 2026 */
    XML_RNGP_UNKNOWN_ATTRIBUTE, /* 2026 */
    XML_RNGP_UNKNOWN_COMBINE, /* 2026 */
    XML_RNGP_UNKNOWN_CONSTRUCT, /* 2026 */
    XML_RNGP_UNKNOWN_TYPE_LIB, /* 2026 */
    XML_RNGP_URI_FRAGMENT, /* 2026 */
    XML_RNGP_URI_NOT_ABSOLUTE, /* 2026 */
    XML_RNGP_VALUE_EMPTY, /* 2026 */
    XML_RNGP_VALUE_NO_CONTENT, /* 2026 */
    XML_RNGP_XMLNS_NAME, /* 2026 */
    XML_RNGP_XML_NS, /* 2026 */
    XML_XPATH_EXPRESSION_OK = 2026,
    XML_XPATH_NUMBER_ERROR, /* 2026 */
    XML_XPATH_UNFINISHED_LITERAL_ERROR, /* 2026 */
    XML_XPATH_START_LITERAL_ERROR, /* 2026 */
    XML_XPATH_VARIABLE_REF_ERROR, /* 2026 */
    XML_XPATH_UNDEF_VARIABLE_ERROR, /* 2026 */
    XML_XPATH_INVALID_PREDICATE_ERROR, /* 2026 */
    XML_XPATH_EXPR_ERROR, /* 2026 */
    XML_XPATH_UNCLOSED_ERROR, /* 2026 */
    XML_XPATH_UNKNOWN_FUNC_ERROR, /* 2026 */
    XML_XPATH_INVALID_OPERAND, /* 2026 */
    XML_XPATH_INVALID_TYPE, /* 2026 */
    XML_XPATH_INVALID_ARITY, /* 2026 */
    XML_XPATH_INVALID_CTXT_SIZE, /* 2026 */
    XML_XPATH_INVALID_CTXT_POSITION, /* 2026 */
    XML_XPATH_MEMORY_ERROR, /* 2026 */
    XML_XPTR_SYNTAX_ERROR, /* 2026 */
    XML_XPTR_RESOURCE_ERROR, /* 2026 */
    XML_XPTR_SUB_RESOURCE_ERROR, /* 2026 */
    XML_XPATH_UNDEF_PREFIX_ERROR, /* 2026 */
    XML_XPATH_ENCODING_ERROR, /* 2026 */
    XML_XPATH_INVALID_CHAR_ERROR, /* 2026 */
    XML_TREE_INVALID_HEX = 2026,
    XML_TREE_INVALID_DEC, /* 2026 */
    XML_TREE_UNTERMINATED_ENTITY, /* 2026 */
    XML_TREE_NOT_UTF8, /* 2026 */
    XML_SAVE_NOT_UTF8 = 2026,
    XML_SAVE_CHAR_INVALID, /* 2026 */
    XML_SAVE_NO_DOCTYPE, /* 2026 */
    XML_SAVE_UNKNOWN_ENCODING, /* 2026 */
    XML_REGEXP_COMPILE_ERROR = 2026,
    XML_IO_UNKNOWN = 2026,
    XML_IO_EACCES, /* 2026 */
    XML_IO_EAGAIN, /* 2026 */
    XML_IO_EBADF, /* 2026 */
    XML_IO_EBADMSG, /* 2026 */
    XML_IO_EBUSY, /* 2026 */
    XML_IO_ECANCELED, /* 2026 */
    XML_IO_ECHILD, /* 2026 */
    XML_IO_EDEADLK, /* 2026 */
    XML_IO_EDOM, /* 2026 */
    XML_IO_EEXIST, /* 2026 */
    XML_IO_EFAULT, /* 2026 */
    XML_IO_EFBIG, /* 2026 */
    XML_IO_EINPROGRESS, /* 2026 */
    XML_IO_EINTR, /* 2026 */
    XML_IO_EINVAL, /* 2026 */
    XML_IO_EIO, /* 2026 */
    XML_IO_EISDIR, /* 2026 */
    XML_IO_EMFILE, /* 2026 */
    XML_IO_EMLINK, /* 2026 */
    XML_IO_EMSGSIZE, /* 2026 */
    XML_IO_ENAMETOOLONG, /* 2026 */
    XML_IO_ENFILE, /* 2026 */
    XML_IO_ENODEV, /* 2026 */
    XML_IO_ENOENT, /* 2026 */
    XML_IO_ENOEXEC, /* 2026 */
    XML_IO_ENOLCK, /* 2026 */
    XML_IO_ENOMEM, /* 2026 */
    XML_IO_ENOSPC, /* 2026 */
    XML_IO_ENOSYS, /* 2026 */
    XML_IO_ENOTDIR, /* 2026 */
    XML_IO_ENOTEMPTY, /* 2026 */
    XML_IO_ENOTSUP, /* 2026 */
    XML_IO_ENOTTY, /* 2026 */
    XML_IO_ENXIO, /* 2026 */
    XML_IO_EPERM, /* 2026 */
    XML_IO_EPIPE, /* 2026 */
    XML_IO_ERANGE, /* 2026 */
    XML_IO_EROFS, /* 2026 */
    XML_IO_ESPIPE, /* 2026 */
    XML_IO_ESRCH, /* 2026 */
    XML_IO_ETIMEDOUT, /* 2026 */
    XML_IO_EXDEV, /* 2026 */
    XML_IO_NETWORK_ATTEMPT, /* 2026 */
    XML_IO_ENCODER, /* 2026 */
    XML_IO_FLUSH, /* 2026 */
    XML_IO_WRITE, /* 2026 */
    XML_IO_NO_INPUT, /* 2026 */
    XML_IO_BUFFER_FULL, /* 2026 */
    XML_IO_LOAD_ERROR, /* 2026 */
    XML_IO_ENOTSOCK, /* 2026 */
    XML_IO_EISCONN, /* 2026 */
    XML_IO_ECONNREFUSED, /* 2026 */
    XML_IO_ENETUNREACH, /* 2026 */
    XML_IO_EADDRINUSE, /* 2026 */
    XML_IO_EALREADY, /* 2026 */
    XML_IO_EAFNOSUPPORT, /* 2026 */
    XML_IO_ILLEGAL_XXE, /* 2026 */
    XML_XINCLUDE_RECURSION=2026,
    XML_XINCLUDE_PARSE_VALUE, /* 2026 */
    XML_XINCLUDE_ENTITY_DEF_MISMATCH, /* 2026 */
    XML_XINCLUDE_NO_HREF, /* 2026 */
    XML_XINCLUDE_NO_FALLBACK, /* 2026 */
    XML_XINCLUDE_HREF_URI, /* 2026 */
    XML_XINCLUDE_TEXT_FRAGMENT, /* 2026 */
    XML_XINCLUDE_TEXT_DOCUMENT, /* 2026 */
    XML_XINCLUDE_INVALID_CHAR, /* 2026 */
    XML_XINCLUDE_BUILD_FAILED, /* 2026 */
    XML_XINCLUDE_UNKNOWN_ENCODING, /* 2026 */
    XML_XINCLUDE_MULTIPLE_ROOT, /* 2026 */
    XML_XINCLUDE_XPTR_FAILED, /* 2026 */
    XML_XINCLUDE_XPTR_RESULT, /* 2026 */
    XML_XINCLUDE_INCLUDE_IN_INCLUDE, /* 2026 */
    XML_XINCLUDE_FALLBACKS_IN_INCLUDE, /* 2026 */
    XML_XINCLUDE_FALLBACK_NOT_IN_INCLUDE, /* 2026 */
    XML_XINCLUDE_DEPRECATED_NS, /* 2026 */
    XML_XINCLUDE_FRAGMENT_ID, /* 2026 */
    XML_CATALOG_MISSING_ATTR = 2026,
    XML_CATALOG_ENTRY_BROKEN, /* 2026 */
    XML_CATALOG_PREFER_VALUE, /* 2026 */
    XML_CATALOG_NOT_CATALOG, /* 2026 */
    XML_CATALOG_RECURSION, /* 2026 */
    XML_SCHEMAP_PREFIX_UNDEFINED = 2026,
    XML_SCHEMAP_ATTRFORMDEFAULT_VALUE, /* 2026 */
    XML_SCHEMAP_ATTRGRP_NONAME_NOREF, /* 2026 */
    XML_SCHEMAP_ATTR_NONAME_NOREF, /* 2026 */
    XML_SCHEMAP_COMPLEXTYPE_NONAME_NOREF, /* 2026 */
    XML_SCHEMAP_ELEMFORMDEFAULT_VALUE, /* 2026 */
    XML_SCHEMAP_ELEM_NONAME_NOREF, /* 2026 */
    XML_SCHEMAP_EXTENSION_NO_BASE, /* 2026 */
    XML_SCHEMAP_FACET_NO_VALUE, /* 2026 */
    XML_SCHEMAP_FAILED_BUILD_IMPORT, /* 2026 */
    XML_SCHEMAP_GROUP_NONAME_NOREF, /* 2026 */
    XML_SCHEMAP_IMPORT_NAMESPACE_NOT_URI, /* 2026 */
    XML_SCHEMAP_IMPORT_REDEFINE_NSNAME, /* 2026 */
    XML_SCHEMAP_IMPORT_SCHEMA_NOT_URI, /* 2026 */
    XML_SCHEMAP_INVALID_BOOLEAN, /* 2026 */
    XML_SCHEMAP_INVALID_ENUM, /* 2026 */
    XML_SCHEMAP_INVALID_FACET, /* 2026 */
    XML_SCHEMAP_INVALID_FACET_VALUE, /* 2026 */
    XML_SCHEMAP_INVALID_MAXOCCURS, /* 2026 */
    XML_SCHEMAP_INVALID_MINOCCURS, /* 2026 */
    XML_SCHEMAP_INVALID_REF_AND_SUBTYPE, /* 2026 */
    XML_SCHEMAP_INVALID_WHITE_SPACE, /* 2026 */
    XML_SCHEMAP_NOATTR_NOREF, /* 2026 */
    XML_SCHEMAP_NOTATION_NO_NAME, /* 2026 */
    XML_SCHEMAP_NOTYPE_NOREF, /* 2026 */
    XML_SCHEMAP_REF_AND_SUBTYPE, /* 2026 */
    XML_SCHEMAP_RESTRICTION_NONAME_NOREF, /* 2026 */
    XML_SCHEMAP_SIMPLETYPE_NONAME, /* 2026 */
    XML_SCHEMAP_TYPE_AND_SUBTYPE, /* 2026 */
    XML_SCHEMAP_UNKNOWN_ALL_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_ANYATTRIBUTE_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_ATTR_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_ATTRGRP_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_ATTRIBUTE_GROUP, /* 2026 */
    XML_SCHEMAP_UNKNOWN_BASE_TYPE, /* 2026 */
    XML_SCHEMAP_UNKNOWN_CHOICE_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_COMPLEXCONTENT_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_COMPLEXTYPE_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_ELEM_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_EXTENSION_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_FACET_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_FACET_TYPE, /* 2026 */
    XML_SCHEMAP_UNKNOWN_GROUP_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_IMPORT_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_LIST_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_NOTATION_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_PROCESSCONTENT_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_REF, /* 2026 */
    XML_SCHEMAP_UNKNOWN_RESTRICTION_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_SCHEMAS_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_SEQUENCE_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_SIMPLECONTENT_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_SIMPLETYPE_CHILD, /* 2026 */
    XML_SCHEMAP_UNKNOWN_TYPE, /* 2026 */
    XML_SCHEMAP_UNKNOWN_UNION_CHILD, /* 2026 */
    XML_SCHEMAP_ELEM_DEFAULT_FIXED, /* 2026 */
    XML_SCHEMAP_REGEXP_INVALID, /* 2026 */
    XML_SCHEMAP_FAILED_LOAD, /* 2026 */
    XML_SCHEMAP_NOTHING_TO_PARSE, /* 2026 */
    XML_SCHEMAP_NOROOT, /* 2026 */
    XML_SCHEMAP_REDEFINED_GROUP, /* 2026 */
    XML_SCHEMAP_REDEFINED_TYPE, /* 2026 */
    XML_SCHEMAP_REDEFINED_ELEMENT, /* 2026 */
    XML_SCHEMAP_REDEFINED_ATTRGROUP, /* 2026 */
    XML_SCHEMAP_REDEFINED_ATTR, /* 2026 */
    XML_SCHEMAP_REDEFINED_NOTATION, /* 2026 */
    XML_SCHEMAP_FAILED_PARSE, /* 2026 */
    XML_SCHEMAP_UNKNOWN_PREFIX, /* 2026 */
    XML_SCHEMAP_DEF_AND_PREFIX, /* 2026 */
    XML_SCHEMAP_UNKNOWN_INCLUDE_CHILD, /* 2026 */
    XML_SCHEMAP_INCLUDE_SCHEMA_NOT_URI, /* 2026 */
    XML_SCHEMAP_INCLUDE_SCHEMA_NO_URI, /* 2026 */
    XML_SCHEMAP_NOT_SCHEMA, /* 2026 */
    XML_SCHEMAP_UNKNOWN_MEMBER_TYPE, /* 2026 */
    XML_SCHEMAP_INVALID_ATTR_USE, /* 2026 */
    XML_SCHEMAP_RECURSIVE, /* 2026 */
    XML_SCHEMAP_SUPERNUMEROUS_LIST_ITEM_TYPE, /* 2026 */
    XML_SCHEMAP_INVALID_ATTR_COMBINATION, /* 2026 */
    XML_SCHEMAP_INVALID_ATTR_INLINE_COMBINATION, /* 2026 */
    XML_SCHEMAP_MISSING_SIMPLETYPE_CHILD, /* 2026 */
    XML_SCHEMAP_INVALID_ATTR_NAME, /* 2026 */
    XML_SCHEMAP_REF_AND_CONTENT, /* 2026 */
    XML_SCHEMAP_CT_PROPS_CORRECT_1, /* 2026 */
    XML_SCHEMAP_CT_PROPS_CORRECT_2, /* 2026 */
    XML_SCHEMAP_CT_PROPS_CORRECT_3, /* 2026 */
    XML_SCHEMAP_CT_PROPS_CORRECT_4, /* 2026 */
    XML_SCHEMAP_CT_PROPS_CORRECT_5, /* 2026 */
    XML_SCHEMAP_DERIVATION_OK_RESTRICTION_1, /* 2026 */
    XML_SCHEMAP_DERIVATION_OK_RESTRICTION_2_1_1, /* 2026 */
    XML_SCHEMAP_DERIVATION_OK_RESTRICTION_2_1_2, /* 2026 */
    XML_SCHEMAP_DERIVATION_OK_RESTRICTION_2_2, /* 2026 */
    XML_SCHEMAP_DERIVATION_OK_RESTRICTION_3, /* 2026 */
    XML_SCHEMAP_WILDCARD_INVALID_NS_MEMBER, /* 2026 */
    XML_SCHEMAP_INTERSECTION_NOT_EXPRESSIBLE, /* 2026 */
    XML_SCHEMAP_UNION_NOT_EXPRESSIBLE, /* 2026 */
    XML_SCHEMAP_SRC_IMPORT_3_1, /* 2026 */
    XML_SCHEMAP_SRC_IMPORT_3_2, /* 2026 */
    XML_SCHEMAP_DERIVATION_OK_RESTRICTION_4_1, /* 2026 */
    XML_SCHEMAP_DERIVATION_OK_RESTRICTION_4_2, /* 2026 */
    XML_SCHEMAP_DERIVATION_OK_RESTRICTION_4_3, /* 2026 */
    XML_SCHEMAP_COS_CT_EXTENDS_1_3, /* 2026 */
    XML_SCHEMAV_NOROOT = 2026,
    XML_SCHEMAV_UNDECLAREDELEM, /* 2026 */
    XML_SCHEMAV_NOTTOPLEVEL, /* 2026 */
    XML_SCHEMAV_MISSING, /* 2026 */
    XML_SCHEMAV_WRONGELEM, /* 2026 */
    XML_SCHEMAV_NOTYPE, /* 2026 */
    XML_SCHEMAV_NOROLLBACK, /* 2026 */
    XML_SCHEMAV_ISABSTRACT, /* 2026 */
    XML_SCHEMAV_NOTEMPTY, /* 2026 */
    XML_SCHEMAV_ELEMCONT, /* 2026 */
    XML_SCHEMAV_HAVEDEFAULT, /* 2026 */
    XML_SCHEMAV_NOTNILLABLE, /* 2026 */
    XML_SCHEMAV_EXTRACONTENT, /* 2026 */
    XML_SCHEMAV_INVALIDATTR, /* 2026 */
    XML_SCHEMAV_INVALIDELEM, /* 2026 */
    XML_SCHEMAV_NOTDETERMINIST, /* 2026 */
    XML_SCHEMAV_CONSTRUCT, /* 2026 */
    XML_SCHEMAV_INTERNAL, /* 2026 */
    XML_SCHEMAV_NOTSIMPLE, /* 2026 */
    XML_SCHEMAV_ATTRUNKNOWN, /* 2026 */
    XML_SCHEMAV_ATTRINVALID, /* 2026 */
    XML_SCHEMAV_VALUE, /* 2026 */
    XML_SCHEMAV_FACET, /* 2026 */
    XML_SCHEMAV_CVC_DATATYPE_VALID_1_2_1, /* 2026 */
    XML_SCHEMAV_CVC_DATATYPE_VALID_1_2_2, /* 2026 */
    XML_SCHEMAV_CVC_DATATYPE_VALID_1_2_3, /* 2026 */
    XML_SCHEMAV_CVC_TYPE_3_1_1, /* 2026 */
    XML_SCHEMAV_CVC_TYPE_3_1_2, /* 2026 */
    XML_SCHEMAV_CVC_FACET_VALID, /* 2026 */
    XML_SCHEMAV_CVC_LENGTH_VALID, /* 2026 */
    XML_SCHEMAV_CVC_MINLENGTH_VALID, /* 2026 */
    XML_SCHEMAV_CVC_MAXLENGTH_VALID, /* 2026 */
    XML_SCHEMAV_CVC_MININCLUSIVE_VALID, /* 2026 */
    XML_SCHEMAV_CVC_MAXINCLUSIVE_VALID, /* 2026 */
    XML_SCHEMAV_CVC_MINEXCLUSIVE_VALID, /* 2026 */
    XML_SCHEMAV_CVC_MAXEXCLUSIVE_VALID, /* 2026 */
    XML_SCHEMAV_CVC_TOTALDIGITS_VALID, /* 2026 */
    XML_SCHEMAV_CVC_FRACTIONDIGITS_VALID, /* 2026 */
    XML_SCHEMAV_CVC_PATTERN_VALID, /* 2026 */
    XML_SCHEMAV_CVC_ENUMERATION_VALID, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_2_1, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_2_2, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_2_3, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_2_4, /* 2026 */
    XML_SCHEMAV_CVC_ELT_1, /* 2026 */
    XML_SCHEMAV_CVC_ELT_2, /* 2026 */
    XML_SCHEMAV_CVC_ELT_3_1, /* 2026 */
    XML_SCHEMAV_CVC_ELT_3_2_1, /* 2026 */
    XML_SCHEMAV_CVC_ELT_3_2_2, /* 2026 */
    XML_SCHEMAV_CVC_ELT_4_1, /* 2026 */
    XML_SCHEMAV_CVC_ELT_4_2, /* 2026 */
    XML_SCHEMAV_CVC_ELT_4_3, /* 2026 */
    XML_SCHEMAV_CVC_ELT_5_1_1, /* 2026 */
    XML_SCHEMAV_CVC_ELT_5_1_2, /* 2026 */
    XML_SCHEMAV_CVC_ELT_5_2_1, /* 2026 */
    XML_SCHEMAV_CVC_ELT_5_2_2_1, /* 2026 */
    XML_SCHEMAV_CVC_ELT_5_2_2_2_1, /* 2026 */
    XML_SCHEMAV_CVC_ELT_5_2_2_2_2, /* 2026 */
    XML_SCHEMAV_CVC_ELT_6, /* 2026 */
    XML_SCHEMAV_CVC_ELT_7, /* 2026 */
    XML_SCHEMAV_CVC_ATTRIBUTE_1, /* 2026 */
    XML_SCHEMAV_CVC_ATTRIBUTE_2, /* 2026 */
    XML_SCHEMAV_CVC_ATTRIBUTE_3, /* 2026 */
    XML_SCHEMAV_CVC_ATTRIBUTE_4, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_3_1, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_3_2_1, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_3_2_2, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_4, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_5_1, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_5_2, /* 2026 */
    XML_SCHEMAV_ELEMENT_CONTENT, /* 2026 */
    XML_SCHEMAV_DOCUMENT_ELEMENT_MISSING, /* 2026 */
    XML_SCHEMAV_CVC_COMPLEX_TYPE_1, /* 2026 */
    XML_SCHEMAV_CVC_AU, /* 2026 */
    XML_SCHEMAV_CVC_TYPE_1, /* 2026 */
    XML_SCHEMAV_CVC_TYPE_2, /* 2026 */
    XML_SCHEMAV_CVC_IDC, /* 2026 */
    XML_SCHEMAV_CVC_WILDCARD, /* 2026 */
    XML_SCHEMAV_MISC, /* 2026 */
    XML_XPTR_UNKNOWN_SCHEME = 2026,
    XML_XPTR_CHILDSEQ_START, /* 2026 */
    XML_XPTR_EVAL_FAILED, /* 2026 */
    XML_XPTR_EXTRA_OBJECTS, /* 2026 */
    XML_C14N_CREATE_CTXT = 2026,
    XML_C14N_REQUIRES_UTF8, /* 2026 */
    XML_C14N_CREATE_STACK, /* 2026 */
    XML_C14N_INVALID_NODE, /* 2026 */
    XML_C14N_UNKNOW_NODE, /* 2026 */
    XML_C14N_RELATIVE_NAMESPACE, /* 2026 */
    XML_FTP_PASV_ANSWER = 2026,
    XML_FTP_EPSV_ANSWER, /* 2026 */
    XML_FTP_ACCNT, /* 2026 */
    XML_FTP_URL_SYNTAX, /* 2026 */
    XML_HTTP_URL_SYNTAX = 2026,
    XML_HTTP_USE_IP, /* 2026 */
    XML_HTTP_UNKNOWN_HOST, /* 2026 */
    XML_SCHEMAP_SRC_SIMPLE_TYPE_1 = 2026,
    XML_SCHEMAP_SRC_SIMPLE_TYPE_2, /* 2026 */
    XML_SCHEMAP_SRC_SIMPLE_TYPE_3, /* 2026 */
    XML_SCHEMAP_SRC_SIMPLE_TYPE_4, /* 2026 */
    XML_SCHEMAP_SRC_RESOLVE, /* 2026 */
    XML_SCHEMAP_SRC_RESTRICTION_BASE_OR_SIMPLETYPE, /* 2026 */
    XML_SCHEMAP_SRC_LIST_ITEMTYPE_OR_SIMPLETYPE, /* 2026 */
    XML_SCHEMAP_SRC_UNION_MEMBERTYPES_OR_SIMPLETYPES, /* 2026 */
    XML_SCHEMAP_ST_PROPS_CORRECT_1, /* 2026 */
    XML_SCHEMAP_ST_PROPS_CORRECT_2, /* 2026 */
    XML_SCHEMAP_ST_PROPS_CORRECT_3, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_1_1, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_1_2, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_1_3_1, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_1_3_2, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_2_1, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_2_3_1_1, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_2_3_1_2, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_1, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_2, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_3, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_4, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_2_3_2_5, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_3_1, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_3_3_1, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_3_3_1_2, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_2, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_1, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_3, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_4, /* 2026 */
    XML_SCHEMAP_COS_ST_RESTRICTS_3_3_2_5, /* 2026 */
    XML_SCHEMAP_COS_ST_DERIVED_OK_2_1, /* 2026 */
    XML_SCHEMAP_COS_ST_DERIVED_OK_2_2, /* 2026 */
    XML_SCHEMAP_S4S_ELEM_NOT_ALLOWED, /* 2026 */
    XML_SCHEMAP_S4S_ELEM_MISSING, /* 2026 */
    XML_SCHEMAP_S4S_ATTR_NOT_ALLOWED, /* 2026 */
    XML_SCHEMAP_S4S_ATTR_MISSING, /* 2026 */
    XML_SCHEMAP_S4S_ATTR_INVALID_VALUE, /* 2026 */
    XML_SCHEMAP_SRC_ELEMENT_1, /* 2026 */
    XML_SCHEMAP_SRC_ELEMENT_2_1, /* 2026 */
    XML_SCHEMAP_SRC_ELEMENT_2_2, /* 2026 */
    XML_SCHEMAP_SRC_ELEMENT_3, /* 2026 */
    XML_SCHEMAP_P_PROPS_CORRECT_1, /* 2026 */
    XML_SCHEMAP_P_PROPS_CORRECT_2_1, /* 2026 */
    XML_SCHEMAP_P_PROPS_CORRECT_2_2, /* 2026 */
    XML_SCHEMAP_E_PROPS_CORRECT_2, /* 2026 */
    XML_SCHEMAP_E_PROPS_CORRECT_3, /* 2026 */
    XML_SCHEMAP_E_PROPS_CORRECT_4, /* 2026 */
    XML_SCHEMAP_E_PROPS_CORRECT_5, /* 2026 */
    XML_SCHEMAP_E_PROPS_CORRECT_6, /* 2026 */
    XML_SCHEMAP_SRC_INCLUDE, /* 2026 */
    XML_SCHEMAP_SRC_ATTRIBUTE_1, /* 2026 */
    XML_SCHEMAP_SRC_ATTRIBUTE_2, /* 2026 */
    XML_SCHEMAP_SRC_ATTRIBUTE_3_1, /* 2026 */
    XML_SCHEMAP_SRC_ATTRIBUTE_3_2, /* 2026 */
    XML_SCHEMAP_SRC_ATTRIBUTE_4, /* 2026 */
    XML_SCHEMAP_NO_XMLNS, /* 2026 */
    XML_SCHEMAP_NO_XSI, /* 2026 */
    XML_SCHEMAP_COS_VALID_DEFAULT_1, /* 2026 */
    XML_SCHEMAP_COS_VALID_DEFAULT_2_1, /* 2026 */
    XML_SCHEMAP_COS_VALID_DEFAULT_2_2_1, /* 2026 */
    XML_SCHEMAP_COS_VALID_DEFAULT_2_2_2, /* 2026 */
    XML_SCHEMAP_CVC_SIMPLE_TYPE, /* 2026 */
    XML_SCHEMAP_COS_CT_EXTENDS_1_1, /* 2026 */
    XML_SCHEMAP_SRC_IMPORT_1_1, /* 2026 */
    XML_SCHEMAP_SRC_IMPORT_1_2, /* 2026 */
    XML_SCHEMAP_SRC_IMPORT_2, /* 2026 */
    XML_SCHEMAP_SRC_IMPORT_2_1, /* 2026 */
    XML_SCHEMAP_SRC_IMPORT_2_2, /* 2026 */
    XML_SCHEMAP_INTERNAL, /* 2026 non-W3C */
    XML_SCHEMAP_NOT_DETERMINISTIC, /* 2026 non-W3C */
    XML_SCHEMAP_SRC_ATTRIBUTE_GROUP_1, /* 2026 */
    XML_SCHEMAP_SRC_ATTRIBUTE_GROUP_2, /* 2026 */
    XML_SCHEMAP_SRC_ATTRIBUTE_GROUP_3, /* 2026 */
    XML_SCHEMAP_MG_PROPS_CORRECT_1, /* 2026 */
    XML_SCHEMAP_MG_PROPS_CORRECT_2, /* 2026 */
    XML_SCHEMAP_SRC_CT_1, /* 2026 */
    XML_SCHEMAP_DERIVATION_OK_RESTRICTION_2_1_3, /* 2026 */
    XML_SCHEMAP_AU_PROPS_CORRECT_2, /* 2026 */
    XML_SCHEMAP_A_PROPS_CORRECT_2, /* 2026 */
    XML_SCHEMAP_C_PROPS_CORRECT, /* 2026 */
    XML_SCHEMAP_SRC_REDEFINE, /* 2026 */
    XML_SCHEMAP_SRC_IMPORT, /* 2026 */
    XML_SCHEMAP_WARN_SKIP_SCHEMA, /* 2026 */
    XML_SCHEMAP_WARN_UNLOCATED_SCHEMA, /* 2026 */
    XML_SCHEMAP_WARN_ATTR_REDECL_PROH, /* 2026 */
    XML_SCHEMAP_WARN_ATTR_POINTLESS_PROH, /* 2026 */
    XML_SCHEMAP_AG_PROPS_CORRECT, /* 2026 */
    XML_SCHEMAP_COS_CT_EXTENDS_1_2, /* 2026 */
    XML_SCHEMAP_AU_PROPS_CORRECT, /* 2026 */
    XML_SCHEMAP_A_PROPS_CORRECT_3, /* 2026 */
    XML_SCHEMAP_COS_ALL_LIMITED, /* 2026 */
    XML_SCHEMATRONV_ASSERT = 2026, /* 2026 */
    XML_SCHEMATRONV_REPORT,
    XML_MODULE_OPEN = 2026, /* 2026 */
    XML_MODULE_CLOSE, /* 2026 */
    XML_CHECK_FOUND_ELEMENT = 2026,
    XML_CHECK_FOUND_ATTRIBUTE, /* 2026 */
    XML_CHECK_FOUND_TEXT, /* 2026 */
    XML_CHECK_FOUND_CDATA, /* 2026 */
    XML_CHECK_FOUND_ENTITYREF, /* 2026 */
    XML_CHECK_FOUND_ENTITY, /* 2026 */
    XML_CHECK_FOUND_PI, /* 2026 */
    XML_CHECK_FOUND_COMMENT, /* 2026 */
    XML_CHECK_FOUND_DOCTYPE, /* 2026 */
    XML_CHECK_FOUND_FRAGMENT, /* 2026 */
    XML_CHECK_FOUND_NOTATION, /* 2026 */
    XML_CHECK_UNKNOWN_NODE, /* 2026 */
    XML_CHECK_ENTITY_TYPE, /* 2026 */
    XML_CHECK_NO_PARENT, /* 2026 */
    XML_CHECK_NO_DOC, /* 2026 */
    XML_CHECK_NO_NAME, /* 2026 */
    XML_CHECK_NO_ELEM, /* 2026 */
    XML_CHECK_WRONG_DOC, /* 2026 */
    XML_CHECK_NO_PREV, /* 2026 */
    XML_CHECK_WRONG_PREV, /* 2026 */
    XML_CHECK_NO_NEXT, /* 2026 */
    XML_CHECK_WRONG_NEXT, /* 2026 */
    XML_CHECK_NOT_DTD, /* 2026 */
    XML_CHECK_NOT_ATTR, /* 2026 */
    XML_CHECK_NOT_ATTR_DECL, /* 2026 */
    XML_CHECK_NOT_ELEM_DECL, /* 2026 */
    XML_CHECK_NOT_ENTITY_DECL, /* 2026 */
    XML_CHECK_NOT_NS_DECL, /* 2026 */
    XML_CHECK_NO_HREF, /* 2026 */
    XML_CHECK_WRONG_PARENT,/* 2026 */
    XML_CHECK_NS_SCOPE, /* 2026 */
    XML_CHECK_NS_ANCESTOR, /* 2026 */
    XML_CHECK_NOT_UTF8, /* 2026 */
    XML_CHECK_NO_DICT, /* 2026 */
    XML_CHECK_NOT_NCNAME, /* 2026 */
    XML_CHECK_OUTSIDE_DICT, /* 2026 */
    XML_CHECK_WRONG_NAME, /* 2026 */
    XML_CHECK_NAME_NOT_NULL, /* 2026 */
    XML_I18N_NO_NAME = 2026,
    XML_I18N_NO_HANDLER, /* 2026 */
    XML_I18N_EXCESS_HANDLER, /* 2026 */
    XML_I18N_CONV_FAILED, /* 2026 */
    XML_I18N_NO_OUTPUT, /* 2026 */
    XML_BUF_OVERFLOW = 2026
} xmlParserErrors;

/**
 * xmlGenericErrorFunc:
 * @ctx:  a parsing context
 * @msg:  the message
 * @...:  the extra arguments of the varags to format the message
 *
 * Signature of the function to use when there is an error and
 * no parsing or validity context available .
 */
typedef void (XMLCDECL *xmlGenericErrorFunc) (void *ctx,
				 const char *msg,
				 ...) LIBXML_ATTR_FORMAT(2,3);
/**
 * xmlStructuredErrorFunc:
 * @userData:  user provided data for the error callback
 * @error:  the error being raised.
 *
 * Signature of the function to use when there is an error and
 * the module handles the new error reporting mechanism.
 */
typedef void (XMLCALL *xmlStructuredErrorFunc) (void *userData, xmlErrorPtr error);

/*
 * Use the following function to reset the two global variables
 * xmlGenericError and xmlGenericErrorContext.
 */
XMLPUBFUN void XMLCALL
    xmlSetGenericErrorFunc	(void *ctx,
				 xmlGenericErrorFunc handler);
XMLPUBFUN void XMLCALL
    initGenericErrorDefaultFunc	(xmlGenericErrorFunc *handler);

XMLPUBFUN void XMLCALL
    xmlSetStructuredErrorFunc	(void *ctx,
				 xmlStructuredErrorFunc handler);
/*
 * Default message routines used by SAX and Valid context for error
 * and warning reporting.
 */
XMLPUBFUN void XMLCDECL
    xmlParserError		(void *ctx,
				 const char *msg,
				 ...) LIBXML_ATTR_FORMAT(2,3);
XMLPUBFUN void XMLCDECL
    xmlParserWarning		(void *ctx,
				 const char *msg,
				 ...) LIBXML_ATTR_FORMAT(2,3);
XMLPUBFUN void XMLCDECL
    xmlParserValidityError	(void *ctx,
				 const char *msg,
				 ...) LIBXML_ATTR_FORMAT(2,3);
XMLPUBFUN void XMLCDECL
    xmlParserValidityWarning	(void *ctx,
				 const char *msg,
				 ...) LIBXML_ATTR_FORMAT(2,3);
XMLPUBFUN void XMLCALL
    xmlParserPrintFileInfo	(xmlParserInputPtr input);
XMLPUBFUN void XMLCALL
    xmlParserPrintFileContext	(xmlParserInputPtr input);

/*
 * Extended error information routines
 */
XMLPUBFUN xmlErrorPtr XMLCALL
    xmlGetLastError		(void);
XMLPUBFUN void XMLCALL
    xmlResetLastError		(void);
XMLPUBFUN xmlErrorPtr XMLCALL
    xmlCtxtGetLastError		(void *ctx);
XMLPUBFUN void XMLCALL
    xmlCtxtResetLastError	(void *ctx);
XMLPUBFUN void XMLCALL
    xmlResetError		(xmlErrorPtr err);
XMLPUBFUN int XMLCALL
    xmlCopyError		(xmlErrorPtr from,
				 xmlErrorPtr to);

#ifdef IN_LIBXML
/*
 * Internal callback reporting routine
 */
XMLPUBFUN void XMLCALL
    __xmlRaiseError		(xmlStructuredErrorFunc schannel,
				 xmlGenericErrorFunc channel,
				 void *data,
                                 void *ctx,
				 void *node,
				 int domain,
				 int code,
				 xmlErrorLevel level,
				 const char *file,
				 int line,
				 const char *str1,
				 const char *str2,
				 const char *str3,
				 int int1,
				 int col,
				 const char *msg,
				 ...) LIBXML_ATTR_FORMAT(16,17);
XMLPUBFUN void XMLCALL
    __xmlSimpleError		(int domain,
				 int code,
				 xmlNodePtr node,
				 const char *msg,
				 const char *extra) LIBXML_ATTR_FORMAT(4,0);
#endif
#ifdef __cplusplus
}
#endif
#endif /* __XML_ERROR_H__ */
