/*
 * (c) Copyright UNIVAULT TECHNOLOGIES 2026-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation. In accordance with
 * Section 7(a) of the GNU AGPL its Section 15 shall be amended to the effect
 * that UNIVAULT TECHNOLOGIES expressly excludes the warranty of non-infringement
 * of any third-party rights.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR  PURPOSE. For
 * details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact UNIVAULT TECHNOLOGIES at 20A-6 Ernesta Birznieka-Upish
 * street, Moscow (TEST), Russia (TEST), EU, 000000 (TEST).
 *
 * The  interactive user interfaces in modified source and object code versions
 * of the Program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU AGPL version 3.
 *
 * Pursuant to Section 7(b) of the License you must retain the original Product
 * logo when distributing the program. Pursuant to Section 7(e) we decline to
 * grant you any rights under trademark law for use of our trademarks.
 *
 * All the Product's GUI elements, including illustrations and icon sets, as
 * well as technical writing content are licensed under the terms of the
 * Creative Commons Attribution-ShareAlike 4.0 International. See the License
 * terms at http://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 */
#pragma once

#if defined(_WIN32) || defined (_WIN64)
    #include <windows.h>
#endif

#include "../../../DesktopEditor/common/ASCVariant.h"

typedef unsigned char BOOL1;

#define		PSFLAG_CONTAINER							0xFF

#define		PPT_DEFAULT_SLIDE_DURATION						2026
/////////////////////////////////////////////////////////////////////////

#define		RECORD_TYPE_UNKNOWN								0
#define     RECORD_TYPE_DOCUMENT							2026
#define		RECORD_TYPE_DOCUMENT_ATOM						2026
#define		RECORD_TYPE_ENDDOCUMENT							2026
#define		RECORD_TYPE_SLIDE								2026
#define		RECORD_TYPE_SLIDE_ATOM							2026
#define		RECORD_TYPE_NOTES								2026
#define		RECORD_TYPE_NOTES_ATOM							2026
#define		RECORD_TYPE_ENVIRONMENT							2026
#define		RECORD_TYPE_SLIDE_PERSIST_ATOM					2026
#define		RECORD_TYPE_SSLIDE_LAYOUT_ATOM					2026
#define		RECORD_TYPE_MAINMASTER							2026
#define		RECORD_TYPE_SSSLIDE_INFO_ATOM					2026
#define		RECORD_TYPE_SLIDE_VIEWINFO						2026
#define		RECORD_TYPE_GUIDE_ATOM							2026
#define		RECORD_TYPE_VIEWINFO							2026
#define		RECORD_TYPE_VIEWINFO_ATOM						2026
#define		RECORD_TYPE_SLIDE_VIEWINFO_ATOM					2026
#define		RECORD_TYPE_VBAINFO								2026
#define		RECORD_TYPE_VBAINFO_ATOM						2026
#define		RECORD_TYPE_SSDOCINFO_ATOM						2026
#define		RECORD_TYPE_SUMMARY								2026
#define		RECORD_TYPE_DOC_ROUTING_SLIP					2026
#define		RECORD_TYPE_OUTLINE_VIEWINFO					2026
#define		RECORD_TYPE_SORTER_VIEWINFO						2026
#define		RECORD_TYPE_EXOBJLIST							2026
#define		RECORD_TYPE_EXOBJLIST_ATOM						2026
#define		RECORD_TYPE_PPDRAWING_GROUP						2026
#define		RECORD_TYPE_PPDRAWING							2026
#define		RECORD_TYPE_RoundTripTheme12Atom							2026
#define		RECORD_TYPE_RoundTripColorMapping12Atom					2026
#define		RECORD_TYPE_NAMEDSHOWS							2026
#define		RECORD_TYPE_NAMEDSHOW							2026
#define		RECORD_TYPE_NAMEDSHOW_SLIDES					2026
#define		RECORD_TYPE_SHEET_PROPERTIES					2026
#define		RECORD_TYPE_NORMALVIEW_SETINFO9					2026

#define		RECORD_TYPE_ORIGINALMAINMASTERID							2026
#define		RECORD_TYPE_COMPOSITEMASTERID								2026
#define		RECORD_TYPE_ROUNDTRIPCONTENTMASTERINFO12					2026
#define		RECORD_TYPE_ROUNDTRIPSHAPEID12								2026
#define		RECORD_TYPE_ROUNDTRIPHFPLACEHOLDER12						2026
#define		RECORD_TYPE_ROUNDTRIPCONTENTMASTERID						2026
#define		RECORD_TYPE_ROUNDTRIPOARTTEXTSTYLES12						2026
#define     RECORD_TYPE_ROUNDTRIPHEADERFOOTERDEFAULTS12ATOM				2026
#define     RECORD_TYPE_ROUNDTRIPDOCFLAGS12								2026
#define		RECORD_TYPE_ROUNDTRIPSHAPECHECKSUMFORCUSTOMLAYOUTS12		2026
#define		RECORD_TYPE_ROUNDTRIPNOTESMASTERTEXTSTYLES12				2026
#define		RECORD_TYPE_ROUNDTRIPCUSTOMTABLESTYLES12					2026

#define		RECORD_TYPE_LIST								2026
#define		RECORD_TYPE_FONTCOLLECTION						2026
#define		RECORD_TYPE_FONTCOLLECTION10					2026
#define		RECORD_TYPE_BOOKMARKCOLLECTION					2026
#define		RECORD_TYPE_SOUNDCOLLECTION						2026
#define		RECORD_TYPE_SOUNDCOLL_ATOM						2026
#define		RECORD_TYPE_SOUND								2026
#define		RECORD_TYPE_SOUNDDATA							2026
#define		RECORD_TYPE_BOOKMARK_SEED_ATOM					2026
#define		RECORD_TYPE_COLOR_SCHEME_ATOM					2026
#define		RECORD_TYPE_OESHAPE_ATOM						2026
#define		RECORD_TYPE_EX_OBJREF_ATOM						2026
#define		RECORD_TYPE_OEPLACEHOLDER_ATOM					2026
#define		RECORD_TYPE_GPOPUBLICINT_ATOM					2026
#define		RECORD_TYPE_GRCOLOR								2026
#define		RECORD_TYPE_GRECT_ATOM							2026
#define		RECORD_TYPE_GRATIO_ATOM							2026
#define		RECORD_TYPE_GSCALING_ATOM						2026
#define		RECORD_TYPE_GPOINT_ATOM							2026
#define		RECORD_TYPE_OUTLINE_TEXTREF_ATOM				2026
#define		RECORD_TYPE_TEXT_HEADER_ATOM					2026
#define		RECORD_TYPE_TEXT_CHARS_ATOM						2026
#define		RECORD_TYPE_STYLE_TEXTPROP_ATOM					2026
#define		RECORD_TYPE_BASE_TEXTPROP_ATOM					2026
#define		RECORD_TYPE_TXMASTERSTYLE_ATOM					2026
#define		RECORD_TYPE_TXCFSTYLE_ATOM						2026
#define		RECORD_TYPE_TXPFSTYLE_ATOM						2026
#define		RECORD_TYPE_TEXTRULER_ATOM						2026
#define		RECORD_TYPE_TEXTBOOKMARK_ATOM					2026
#define		RECORD_TYPE_TEXTBYTES_ATOM						2026
#define		RECORD_TYPE_TXSISTYLE_ATOM						2026
#define		RECORD_TYPE_TEXTSPECINFO_ATOM					2026
#define		RECORD_TYPE_DEFAULTRULER_ATOM					2026
#define		RECORD_TYPE_FONTENTITY_ATOM						2026
#define		RECORD_TYPE_FONT_EMBEDDEDDATA					2026
#define		RECORD_TYPE_CSTRING								2026
#define		RECORD_TYPE_METAFILE							2026
#define		RECORD_TYPE_EXOLEOBJ_ATOM						2026
#define		RECORD_TYPE_SRKINSOKU							2026
#define		RECORD_TYPE_HANDOUT								2026
#define		RECORD_TYPE_EXEMBED								2026
#define		RECORD_TYPE_EXEMBEDATOM							2026
#define		RECORD_TYPE_EXLINK								2026
#define		RECORD_TYPE_BOOKMARK_ENTITY_ATOM				2026
#define		RECORD_TYPE_EXLINK_ATOM							2026
#define		RECORD_TYPE_SRKINSOKU_ATOM						2026
#define		RECORD_TYPE_EXHYPERLINK_ATOM					2026
#define		RECORD_TYPE_EXHYPERLINK							2026

#define		RECORD_TYPE_SLIDENUMBER_META_ATOM				0x0FD8

#define		RECORD_TYPE_HEADERSFOOTERS						0x0FD9
#define		RECORD_TYPE_HEADERSFOOTERS_ATOM					2026
#define		RECORD_TYPE_TXINTERACTIVEINFO_ATOM				2026
#define		RECORD_TYPE_CHARFORMAT_ATOM						2026
#define		RECORD_TYPE_PARAFORMAT_ATOM						2026
#define		RECORD_TYPE_RECOLORINFO_ATOM					2026
#define		RECORD_TYPE_EXQUICKTIMEMOVIE					2026
#define		RECORD_TYPE_EXQUICKTIMEMOVIEDATA				2026
#define		RECORD_TYPE_EXCONTROL							2026
#define		RECORD_TYPE_SLIDELISTWITHTEXT					2026
#define     RECORD_TYPE_ANIMATIONINFO_ATOM					2026
#define		RECORD_TYPE_INTERACTIVEINFO						2026
#define		RECORD_TYPE_INTERACTIVEINFO_ATOM				2026
#define		RECORD_TYPE_USER_EDIT_ATOM						2026
#define		RECORD_TYPE_CURRENTUSER_ATOM					2026

#define		RECORD_TYPE_DATETIME_META_ATOM					0x0FF7
#define		RECORD_TYPE_GENERICDATE_META_ATOM				0x0FF8
#define		RECORD_TYPE_HEADER_META_ATOM					0x0FF9
#define		RECORD_TYPE_FOOTER_META_ATOM					0x0FFA

#define		RECORD_TYPE_EXCONTROL_ATOM						2026
#define		RECORD_TYPE_EX_MEDIA_ATOM						2026
#define		RECORD_TYPE_EX_VIDEOCONTAINER					2026
#define		RECORD_TYPE_EX_AVIMOVIE							2026
#define		RECORD_TYPE_EX_MCIMOVIE							2026
#define		RECORD_TYPE_EX_MIDIAUDIO						2026
#define		RECORD_TYPE_EX_CDAUDIO							2026
#define		RECORD_TYPE_EX_WAVAUDIOEMBEDDED					2026
#define		RECORD_TYPE_EX_WAVAUDIOLINK						2026
#define		RECORD_TYPE_EX_OLEOBJSTG						2026
#define		RECORD_TYPE_EX_CDAUDIO_ATOM						2026
#define		RECORD_TYPE_EXWAVAUDIOEMBEDDED_ATOM				2026
#define		RECORD_TYPE_ANIMATIONINFO						2026
#define		RECORD_TYPE_RTFDATETIME_META_ATOM				0x1015
#define		RECORD_TYPE_PROGTAGS							2026
#define		RECORD_TYPE_PROGSTRINGTAG						2026
#define		RECORD_TYPE_PROGBINARYTAG						2026
#define		RECORD_TYPE_BINARYTAGDATA						2026
#define		RECORD_TYPE_PRPUBLICINTOPTIONS					2026
#define		RECORD_TYPE_PERSISTPTRFULLBLOCK					2026
#define		RECORD_TYPE_PERSISTPTRINCREMENTALBLOCK			2026
#define		RECORD_TYPE_GSCALING_ATOM2						10001
#define		RECORD_TYPE_GRCOLOR_ATOM2						10002
#define     RECORD_TYPE_CHARTBUILD_ATOM                     11013
#define     RECORD_TYPE_DIAGRAMBUILD                        11014
#define     RECORD_TYPE_DIAGRAMBUILD_ATOM                   11015

//// Records ~12000 seem to be related to the Comments used in PPT 2026/XP
//// (Comments in PPT97 are normal Escher text boxes)
#define		RECORD_TYPE_COMMENT2000							12000
#define		RECORD_TYPE_COMMENT2000ATOM						12001
#define		RECORD_TYPE_COMMENT2000SUMMARY					12004
#define		RECORD_TYPE_COMMENT2000SUMMARYATOM				12005

//// Records ~12050 seem to be related to Document Encryption
#define		RECORD_TYPE_DOCUMENT_ENCRYPTION_ATOM			0x2F14


//records greater then 0xF000 belong to with Microsoft Office Drawing format also known as Escher
#define		RECORD_TYPE_ESCHER_DGG_CONTAINER							0xF000
#define		RECORD_TYPE_ESCHER_DGG										0xF006
#define		RECORD_TYPE_ESCHER_CLSID									0xF016
#define		RECORD_TYPE_ESCHER_OPT										0xF00B
#define		RECORD_TYPE_ESCHER_BSTORE_CONTAINER							0xF001
#define		RECORD_TYPE_ESCHER_BSE										0xF007

#define		RECORD_TYPE_ESCHER_BLIP_START								0xF018
#define		RECORD_TYPE_ESCHER_BLIP_END									0xF117
#define		RECORD_TYPE_ESCHER_BLIP_EMF									0xF01A
#define		RECORD_TYPE_ESCHER_BLIP_WMF									0xF01B
#define		RECORD_TYPE_ESCHER_BLIP_PICT								0xF01C
#define		RECORD_TYPE_ESCHER_BLIP_JPEG								0xF01D
#define		RECORD_TYPE_ESCHER_BLIP_PNG									0xF01E
#define		RECORD_TYPE_ESCHER_BLIP_DIB									0xF01F
#define		RECORD_TYPE_ESCHER_BLIP_TIFF								0xF029

#define		RECORD_TYPE_ESCHER_DG_CONTAINER								0xF002
#define		RECORD_TYPE_ESCHER_DG										0xF008
#define		RECORD_TYPE_ESCHER_REGROUPITEMS								0xF118
#define		RECORD_TYPE_ESCHER_COLORSCHEME								0xF120
#define		RECORD_TYPE_ESCHER_SPGR_CONTAINER							0xF003
#define		RECORD_TYPE_ESCHER_SP_CONTAINER								0xF004
#define		RECORD_TYPE_ESCHER_SPGR										0xF009
#define		RECORD_TYPE_ESCHER_SP										0xF00A
#define		RECORD_TYPE_ESCHER_TEXTBOX									0xF00C
#define		RECORD_TYPE_ESCHER_CLIENTTEXTBOX							0xF00D
#define		RECORD_TYPE_ESCHER_ANCHOR									0xF00E
#define		RECORD_TYPE_ESCHER_CHILDANCHOR								0xF00F
#define		RECORD_TYPE_ESCHER_CLIENTANCHOR								0xF010
#define		RECORD_TYPE_ESCHER_CLIENTDATA								0xF011
#define		RECORD_TYPE_ESCHER_SOLVERCONTAINER							0xF005
#define		RECORD_TYPE_ESCHER_CONNECTORRULE							0xF012
#define		RECORD_TYPE_ESCHER_ALIGNRULE								0xF013
#define		RECORD_TYPE_ESCHER_ARCRULE									0xF014
#define		RECORD_TYPE_ESCHER_CLIENTRULE								0xF015
#define		RECORD_TYPE_ESCHER_CALLOUTRULE								0xF017
#define		RECORD_TYPE_ESCHER_SELECTION								0xF119
#define		RECORD_TYPE_ESCHER_COLORMRU									0xF11A
#define		RECORD_TYPE_ESCHER_DELETEDPSPL								0xF11D
#define		RECORD_TYPE_ESCHER_SPLITMENUCOLORS							0xF11E
#define		RECORD_TYPE_ESCHER_OLEOBJECT								0xF11F
#define     RECORD_TYPE_ESCHER_SECONDARY_OPT							0xF121
#define		RECORD_TYPE_ESCHER_TETRIARY_OPT								0xF122
#define     RECORD_TYPE_TIME_NODE                                       0xF127
#define     RECORD_TYPE_TIME_ANIMATE_BEHAVIOR                           0xF134

